# Generated by Django 5.2.8 on 2025-11-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIMCSAlumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='register',
            name='Batch',
            field=models.IntegerField(default=0),
        ),
    ]
