# Generated by Django 5.2.8 on 2026-01-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIMCSAlumni', '0002_register_email_alter_register_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
